### ISSUE TITLE
Environnement node

### ISSUE THREAD

**Issue by profy12** [O-clock-Dev/teleporter-compose#16]
L'exécution du processus node est pour l'instant mal définie, je pense à quelque chose comme ça :

- il nous faut deux services, un de back et un de front, chacun son container.
- utiliser le terminal et `teleport teleporteur-node` pour lancer le process -> le shell est un peu pourri à voir ...
- il faut utiliser un routage par vhost pour l'accessibilité distante, peut être deux services un node-front.prenom-nom.localhost et node-back.prenom-nom.localhost.
- on proxifie ces deux services dans haproxy sans check (pour éviter les effets up and down), vers le port 3000 de chaque container.

**Comment by clementgoclock** [comment]
Tu peux faire un `docker compose config` pour voir la config node actuelle qui pop un max de port local/bindé *sifflote*

**Comment by profy12** [comment]
Pour propager l'environnement node, on peut aussi au final rester sur un/des containers dédié node et jouer avec des alias bash (alias npm/node docker run/exec) pour simuler leur présence locale.
D'ailleurs pour le cli mysql on aurait du faire comme ça.
Bon après c'est du Docker in docker, le gars qui lance le process node et fait un ss derrière va pas comprendre.
L'avantage de l'alias docker exec est d'avoir un statut de l'application qui apparait dans la page d'accueil (container qui tourne -> up)
