### ISSUE TITLE
Séparation compose core / app

### ISSUE THREAD

**Issue by profy12** [O-clock-Dev/teleporter-compose#19]
Il faut différencier nos deux fichiers compose selon leur criticité et donc ceux qui les modifieront :
- une partie `core` avec avec tous les containers associés au fonctionnement vital du teleporteur compose (vpn, haproxy, homepage, terminal, filebrowser, templateconfig, autoheal).
- une partie `app` avec un fichier qui pourra être modifié/adapté selon les besoins et les évolutions pédagogiques (caddyserver, adminer, phpmyadmin, mongo-express, vscode-server, node, php, node, postgreSQL, MariaDB, MongoDB).

**Comment by clementgoclock** [comment]
Si on veut ajouter d'autres trucs c'est p'tet le moment de les mettre ici avant qu'on modifie ?
