### ISSUE TITLE
Générer services.yaml si le vpn.env est absent

### ISSUE THREAD

**Issue by profy12** [O-clock-Dev/teleporter-compose#33]
![image](https://github.com/O-clock-Dev/teleporter-compose/assets/3660402/6260e6dc-0dbd-4126-b9fa-2396e79dcaf2)

Si vpn.env n'est pas là, ou vide, il faut que les liens du bas ai un autre format, actuellement on veut pas de reddit/youtube.

**Comment by clementgoclock** [comment]
bookmarks -> services.yaml

**Comment by profy12** [comment]
Indeed, this is broken 
![image](https://github.com/O-clock-Dev/teleporter-compose/assets/3660402/7c5ea8c5-6ab3-4c9e-a4be-766d54999a17)
