### ISSUE TITLE
Automatic start of docker compose services

### ISSUE THREAD

**Issue by profy12** [O-clock-Dev/teleporter-compose#87]
UX test with student show it's better to automatic start every services in the docker compose.

After the initial setup, student will have to only start Docker Desktop every Day (nothink to do with Docker engine).

**Comment by profy12** [comment]
we can also find a way to avoid to run docker compose up in a terminal.

**Comment by clementgoclock** [comment]
As I've seen with Docker Desktop, it starts automatically when DD is launched. We just need to check and adapt things like “running always”.

**Comment by clementgoclock** [comment]
Just launched DD:

![image](https://github.com/O-clock-Dev/teleporter-compose/assets/126659374/6902bcd1-e917-4580-895c-aa5ad037c2e5)

**Comment by profy12** [comment]
indeed, teleporter-templating-config should be sometimes restarted bye not always. The auto heal can be a soluce, or another scheduler containers, samethink simular to a rundeck container but simplier.

**Comment by clementgoclock** [comment]
It's done here with #99 right ?
